import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { files, repoName, token } = await req.json();

    if (!token || !repoName || !files || Object.keys(files).length === 0) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // 1. Authenticate and get user
    const userRes = await fetch("https://api.github.com/user", {
      headers: { 
        Authorization: `Bearer ${token}`,
        "User-Agent": "Nova-AI-App-Builder"
      }
    });
    
    if (!userRes.ok) {
      const err = await userRes.json();
      throw new Error(`Invalid GitHub Token: ${err.message}`);
    }
    const user = await userRes.json();
    const owner = user.login;

    // 2. Create Repository
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: { 
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "Nova-AI-App-Builder"
      },
      body: JSON.stringify({
        name: repoName,
        private: false,
        description: "Generated by Nova AI App Builder",
        auto_init: true
      })
    });
    
    let repoUrl = `https://github.com/${owner}/${repoName}`;
    
    if (!createRes.ok && createRes.status !== 422) {
       const err = await createRes.json();
       throw new Error(`Failed to create repository: ${err.message}`);
    }

    // 3. Upload files
    // Wait briefly for auto_init to complete on GitHub's end
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Upload package.json to ensure it's a valid project if not present
    const projectFiles = { ...files };
    if (!projectFiles['/package.json'] && !projectFiles['package.json']) {
      projectFiles['/package.json'] = JSON.stringify({
        name: repoName,
        version: "0.1.0",
        private: true,
        dependencies: {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "lucide-react": "^0.263.1"
        }
      }, null, 2);
    }

    for (const [path, content] of Object.entries(projectFiles)) {
      const cleanPath = path.startsWith('/') ? path.substring(1) : path;
      
      const putRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/contents/${cleanPath}`, {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
          "User-Agent": "Nova-AI-App-Builder"
        },
        body: JSON.stringify({
          message: `feat: Add ${cleanPath} from Nova AI`,
          content: Buffer.from(content as string).toString("base64")
        })
      });

      if (!putRes.ok && putRes.status !== 422) {
         console.warn(`[Nova GitHub Deploy] Warning: Failed to upload ${cleanPath}`);
      }
    }

    return NextResponse.json({ success: true, url: repoUrl });

  } catch (error: any) {
    console.error("GitHub push error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
